"""gen_claw_pinhole — the fleet re-derives the address it needs (2026-07-29).

The claw NATS pinhole hardcoded the uplink AREDN node's WAN address. That
address is handed out by a router this fleet does not administer; the node
rebooted, the lease moved, the pinhole kept the old value, and every SYN from a
healthy claw was dropped for 6.5 h.

A DHCP reservation was considered and REJECTED for the same reason this fleet
rejected router-side DNS: it makes fleet reachability contingent on config in a
box outside the domain. So the fleet re-derives the address from the uplink MAC,
which is the thing that does not change when a lease moves.

These tests pin the invariants that matter for a script that REWRITES A
FIREWALL. Each one is a way this could sever the claw it exists to protect.
"""

import json
import os
import subprocess
import sys

import pytest

SCRIPT = os.path.join(os.path.dirname(__file__), "..", "scripts",
                      "gen_claw_pinhole.py")

MAC = "02:00:5e:00:11:22"
UPLINK_NOW = "192.0.2.250"
UPLINK_OLD = "192.0.2.24"
PEER = "192.0.2.32"

ARP_HEADER = ("IP address       HW type     Flags       "
              "HW address            Mask     Device\n")

BEGIN = "# BEGIN meshforge claw pinhole (generated by scripts/gen_claw_pinhole.py)"
END = "# END meshforge claw pinhole"


def _arp(rows):
    out = ARP_HEADER
    for ip, flags, mac in rows:
        out += f"{ip:<17}0x1         {flags:<12}{mac:<22}*        eth0\n"
    return out


def _nft(allow, port=4222, managed=True):
    inner = "\t\tip saddr { %s } tcp dport %d accept\n" % (", ".join(allow), port)
    if managed:
        inner = BEGIN + "\n" + inner + END + "\n"
    return (
        "#!/usr/sbin/nft -f\nflush ruleset\ntable inet filter {\n\tchain input {\n"
        "\t\ttype filter hook input priority filter; policy accept;\n"
        '\t\tiifname "lo" tcp dport %d accept\n' % port
        + inner +
        "\t\ttcp dport %d drop\n\t}\n}\n" % port
    )


class Harness:
    def __init__(self, tmp_path):
        self.tmp = tmp_path
        self.nft = tmp_path / "nftables.conf"
        self.arp = tmp_path / "arp"
        self.cfg = tmp_path / "claw_uplink_nodes.json"

    def write(self, *, allow, arp_rows, nodes=None, managed=True):
        self.nft.write_text(_nft(allow, managed=managed))
        self.arp.write_text(_arp(arp_rows))
        self.cfg.write_text(json.dumps(nodes if nodes is not None else [
            {"name": "UPLINK", "mac": MAC, "serves": ["dudeclaw-01"]}]))

    def run(self, mode):
        return subprocess.run(
            [sys.executable, SCRIPT, mode, "--nft-file", str(self.nft),
             "--arp-file", str(self.arp), "--config", str(self.cfg)],
            capture_output=True, text=True, timeout=60)


@pytest.fixture
def h(tmp_path):
    return Harness(tmp_path)


class TestDriftDetection:

    def test_todays_outage_is_detected(self):
        pass  # covered by test_check_reports_drift_when_lease_moved

    def test_check_reports_drift_when_lease_moved(self, h):
        """THE case: node now at .250, pinhole still admits .24."""
        h.write(allow=[PEER, UPLINK_OLD], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        r = h.run("--check")
        assert r.returncode == 1, r.stdout + r.stderr
        assert "DRIFT" in r.stdout
        assert UPLINK_NOW in r.stdout

    def test_in_sync_when_pinhole_admits_current_address(self, h):
        h.write(allow=[PEER, UPLINK_NOW], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        r = h.run("--check")
        assert r.returncode == 0, r.stdout + r.stderr
        assert "in sync" in r.stdout


class TestNeverSeversTheClaw:
    """Each of these is a way an automatic firewall rewriter could cut off the
    thing it protects. They are the reason this script is allowed to run."""

    def test_unobserved_uplink_holds_existing_entries(self, h):
        """MAC absent from arp = we have not talked to it. Dropping its entry
        would sever a working claw on the strength of our own blindness."""
        h.write(allow=[PEER, UPLINK_OLD], arp_rows=[(PEER, "0x2", "aa:bb:cc:dd:ee:ff")])
        r = h.run("--check")
        assert "HOLDING existing allowlist" in r.stdout
        assert r.returncode == 0, "held state must read as in-sync, not drift"

    def test_incomplete_arp_row_is_not_a_location(self, h):
        """Flags 0x0 = a resolution that FAILED. Probing a stale address creates
        exactly this row, so a flags-blind reader would rewrite the firewall
        based on the ghost of its own failed ping."""
        h.write(allow=[PEER, UPLINK_NOW],
                arp_rows=[(UPLINK_NOW, "0x2", MAC), (UPLINK_OLD, "0x0", MAC)])
        r = h.run("--check")
        assert r.returncode == 0, "an INCOMPLETE row was treated as an address"
        assert UPLINK_OLD not in r.stdout.split("should admit")[-1]

    def test_never_renders_an_empty_allowlist(self, h):
        """An empty render cuts off every claw — refuse, report unobservable."""
        h.write(allow=[], arp_rows=[], nodes=[{"name": "UPLINK", "mac": MAC}])
        r = h.run("--check")
        assert r.returncode == 2, r.stdout
        assert "NOBODY" in r.stdout or "UNOBSERVABLE" in r.stdout

    def test_unattributable_entries_are_kept_and_reported(self, h):
        """A repair must not silently delete firewall rules it cannot explain."""
        h.write(allow=[PEER, "192.0.2.77"], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        r = h.run("--check")
        assert "unattributable" in r.stdout
        assert "192.0.2.77" in r.stdout

    def test_missing_managed_region_refuses_to_guess(self, h):
        """Without markers it will not choose a place in a firewall to inject."""
        h.write(allow=[PEER, UPLINK_OLD], arp_rows=[(UPLINK_NOW, "0x2", MAC)],
                managed=False)
        r = h.run("--apply")
        assert r.returncode == 1
        assert "no managed region" in r.stdout


class TestUnobservableNeverWrites:

    def test_absent_declaration_is_unobservable(self, h):
        h.write(allow=[PEER], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        h.cfg.unlink()
        r = h.run("--check")
        assert r.returncode == 2
        assert "UNOBSERVABLE" in r.stdout

    def test_malformed_declaration_is_unobservable(self, h):
        h.write(allow=[PEER], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        h.cfg.write_text("{not json")
        r = h.run("--check")
        assert r.returncode == 2

    def test_unreadable_arp_is_unobservable(self, h):
        h.write(allow=[PEER], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        h.arp.unlink()
        r = h.run("--check")
        assert r.returncode == 2


class TestRenderShape:

    def test_print_emits_a_managed_region(self, h):
        h.write(allow=[PEER, UPLINK_NOW], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        r = h.run("--print")
        assert r.returncode == 0
        assert BEGIN in r.stdout and END in r.stdout
        assert "tcp dport 4222 accept" in r.stdout
        assert "Do not hand-edit" in r.stdout

    def test_extra_allow_is_honoured(self, h):
        h.write(allow=[UPLINK_NOW], arp_rows=[(UPLINK_NOW, "0x2", MAC)],
                nodes=[{"name": "UPLINK", "mac": MAC, "extra_allow": [PEER]}])
        r = h.run("--print")
        assert PEER in r.stdout and UPLINK_NOW in r.stdout
