"""gen_claw_pinhole — the fleet re-derives the address it needs (2026-07-29).

The claw NATS pinhole hardcoded the uplink AREDN node's WAN address. That
address is handed out by a router this fleet does not administer; the node
rebooted, the lease moved, the pinhole kept the old value, and every SYN from a
healthy claw was dropped for 6.5 h.

A DHCP reservation was considered and REJECTED for the same reason this fleet
rejected router-side DNS: it makes fleet reachability contingent on config in a
box outside the domain. So the fleet re-derives the address from the uplink MAC,
which is the thing that does not change when a lease moves.

These tests pin the invariants that matter for a script that REWRITES A
FIREWALL. Each one is a way this could sever the claw it exists to protect.
"""

import json
import os
import subprocess
import sys

import pytest

SCRIPT = os.path.join(os.path.dirname(__file__), "..", "scripts",
                      "gen_claw_pinhole.py")

MAC = "02:00:5e:00:11:22"
UPLINK_NOW = "192.0.2.250"
UPLINK_OLD = "192.0.2.24"
PEER = "192.0.2.32"

ARP_HEADER = ("IP address       HW type     Flags       "
              "HW address            Mask     Device\n")

BEGIN = "# BEGIN meshforge claw pinhole (generated by scripts/gen_claw_pinhole.py)"
END = "# END meshforge claw pinhole"


def _arp(rows):
    out = ARP_HEADER
    for ip, flags, mac in rows:
        out += f"{ip:<17}0x1         {flags:<12}{mac:<22}*        eth0\n"
    return out


def _nft(allow, port=4222, managed=True):
    inner = "\t\tip saddr { %s } tcp dport %d accept\n" % (", ".join(allow), port)
    if managed:
        inner = BEGIN + "\n" + inner + END + "\n"
    return (
        "#!/usr/sbin/nft -f\nflush ruleset\ntable inet filter {\n\tchain input {\n"
        "\t\ttype filter hook input priority filter; policy accept;\n"
        '\t\tiifname "lo" tcp dport %d accept\n' % port
        + inner +
        "\t\ttcp dport %d drop\n\t}\n}\n" % port
    )


class Harness:
    def __init__(self, tmp_path):
        self.tmp = tmp_path
        self.nft = tmp_path / "nftables.conf"
        self.arp = tmp_path / "arp"
        self.cfg = tmp_path / "claw_uplink_nodes.json"

    def write(self, *, allow, arp_rows, nodes=None, managed=True):
        self.nft.write_text(_nft(allow, managed=managed))
        self.arp.write_text(_arp(arp_rows))
        self.cfg.write_text(json.dumps(nodes if nodes is not None else [
            {"name": "UPLINK", "mac": MAC, "serves": ["dudeclaw-01"]}]))

    def run(self, mode):
        return subprocess.run(
            [sys.executable, SCRIPT, mode, "--nft-file", str(self.nft),
             "--arp-file", str(self.arp), "--config", str(self.cfg)],
            capture_output=True, text=True, timeout=60)


@pytest.fixture
def h(tmp_path):
    return Harness(tmp_path)


class TestDriftDetection:

    def test_todays_outage_is_detected(self):
        pass  # covered by test_check_reports_drift_when_lease_moved

    def test_check_reports_drift_when_lease_moved(self, h):
        """THE case: node now at .250, pinhole still admits .24."""
        h.write(allow=[PEER, UPLINK_OLD], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        r = h.run("--check")
        assert r.returncode == 1, r.stdout + r.stderr
        assert "DRIFT" in r.stdout
        assert UPLINK_NOW in r.stdout

    def test_in_sync_when_pinhole_admits_current_address(self, h):
        h.write(allow=[PEER, UPLINK_NOW], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        r = h.run("--check")
        assert r.returncode == 0, r.stdout + r.stderr
        assert "in sync" in r.stdout


class TestNeverSeversTheClaw:
    """Each of these is a way an automatic firewall rewriter could cut off the
    thing it protects. They are the reason this script is allowed to run."""

    def test_unobserved_uplink_holds_existing_entries(self, h):
        """MAC absent from arp = we have not talked to it. Dropping its entry
        would sever a working claw on the strength of our own blindness."""
        h.write(allow=[PEER, UPLINK_OLD], arp_rows=[(PEER, "0x2", "aa:bb:cc:dd:ee:ff")])
        r = h.run("--check")
        assert "HOLDING existing allowlist" in r.stdout
        assert r.returncode == 0, "held state must read as in-sync, not drift"

    def test_incomplete_arp_row_is_not_a_location(self, h):
        """Flags 0x0 = a resolution that FAILED. Probing a stale address creates
        exactly this row, so a flags-blind reader would rewrite the firewall
        based on the ghost of its own failed ping."""
        h.write(allow=[PEER, UPLINK_NOW],
                arp_rows=[(UPLINK_NOW, "0x2", MAC), (UPLINK_OLD, "0x0", MAC)])
        r = h.run("--check")
        assert r.returncode == 0, "an INCOMPLETE row was treated as an address"
        assert UPLINK_OLD not in r.stdout.split("should admit")[-1]

    def test_never_renders_an_empty_allowlist(self, h):
        """An empty render cuts off every claw — refuse, report unobservable."""
        h.write(allow=[], arp_rows=[], nodes=[{"name": "UPLINK", "mac": MAC}])
        r = h.run("--check")
        assert r.returncode == 2, r.stdout
        assert "NOBODY" in r.stdout or "UNOBSERVABLE" in r.stdout

    def test_unattributable_entries_are_kept_and_reported(self, h):
        """A repair must not silently delete firewall rules it cannot explain."""
        h.write(allow=[PEER, "192.0.2.77"], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        r = h.run("--check")
        assert "unattributable" in r.stdout
        assert "192.0.2.77" in r.stdout

    def test_missing_managed_region_refuses_to_guess(self, h):
        """Without markers it will not choose a place in a firewall to inject."""
        h.write(allow=[PEER, UPLINK_OLD], arp_rows=[(UPLINK_NOW, "0x2", MAC)],
                managed=False)
        r = h.run("--apply")
        assert r.returncode == 1
        assert "no managed region" in r.stdout


class TestUnobservableNeverWrites:

    def test_absent_declaration_is_unobservable(self, h):
        h.write(allow=[PEER], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        h.cfg.unlink()
        r = h.run("--check")
        assert r.returncode == 2
        assert "UNOBSERVABLE" in r.stdout

    def test_malformed_declaration_is_unobservable(self, h):
        h.write(allow=[PEER], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        h.cfg.write_text("{not json")
        r = h.run("--check")
        assert r.returncode == 2

    def test_unreadable_arp_is_unobservable(self, h):
        h.write(allow=[PEER], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        h.arp.unlink()
        r = h.run("--check")
        assert r.returncode == 2


class TestRenderShape:

    def test_print_emits_a_managed_region(self, h):
        h.write(allow=[PEER, UPLINK_NOW], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        r = h.run("--print")
        assert r.returncode == 0
        assert BEGIN in r.stdout and END in r.stdout
        assert "tcp dport 4222 accept" in r.stdout
        assert "Do not hand-edit" in r.stdout

    def test_extra_allow_is_honoured(self, h):
        h.write(allow=[UPLINK_NOW], arp_rows=[(UPLINK_NOW, "0x2", MAC)],
                nodes=[{"name": "UPLINK", "mac": MAC, "extra_allow": [PEER]}])
        r = h.run("--print")
        assert PEER in r.stdout and UPLINK_NOW in r.stdout


class TestAttributedPruning:
    """Closing the residue: a lease move used to leave the OLD address in the
    allowlist forever, because the healer keeps what it cannot attribute
    (invariant 4). On an unreserved segment each leftover is a standing permit
    to the NATS bus that some future unrelated device could inherit.

    State makes the old address ATTRIBUTABLE, so it can be removed without
    ever guessing. Deletion in a firewall writer is the riskiest thing in this
    script, so it requires ALL FOUR conditions; every test below is one of the
    ways a looser rule would remove something it should not have.
    """

    def _state(self, h, mapping):
        p = h.tmp / "pinhole_state.json"
        p.write_text(json.dumps({"rendered": mapping}))
        return str(p)

    def _run(self, h, mode, state=None):
        cmd = [sys.executable, SCRIPT, mode, "--nft-file", str(h.nft),
               "--arp-file", str(h.arp), "--config", str(h.cfg)]
        if state:
            cmd += ["--state-file", state]
        return subprocess.run(cmd, capture_output=True, text=True, timeout=60)

    def test_old_address_is_pruned_when_state_attributes_it(self, h):
        """The whole point: state says we rendered .24 for this MAC, the MAC is
        now at .250, and .24 belongs to nobody else -> remove it."""
        h.write(allow=[PEER, UPLINK_OLD, UPLINK_NOW],
                arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        st = self._state(h, {MAC: [UPLINK_OLD]})
        r = self._run(h, "--print", st)
        # Assert on the RENDERED region, not the whole stream: the prune note
        # deliberately names the address it removed, so a naive substring check
        # over stdout would fail on the explanation rather than the outcome.
        region = r.stdout.split(BEGIN, 1)[-1]
        assert UPLINK_NOW in region
        assert UPLINK_OLD not in region, "attributable stale entry was not pruned"
        assert PEER in region, "an unrelated peer must never be pruned"
        assert "pruning %s" % UPLINK_OLD in r.stdout, "a prune must leave a witness"

    def test_without_state_it_keeps_and_reports_as_before(self, h):
        """Back-compat: no state file = no attribution = keep + report. A fresh
        box must not start deleting rules it has no history for."""
        h.write(allow=[PEER, UPLINK_OLD, UPLINK_NOW],
                arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        r = self._run(h, "--check")
        assert UPLINK_OLD in r.stdout
        assert "unattributable" in r.stdout

    def test_never_prunes_a_currently_observed_address(self, h):
        """Even if state names it, an address the MAC is observed at RIGHT NOW
        is live — pruning it would sever the claw this protects."""
        h.write(allow=[PEER, UPLINK_NOW], arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        st = self._state(h, {MAC: [UPLINK_NOW]})
        r = self._run(h, "--print", st)
        assert UPLINK_NOW in r.stdout, "pruned a LIVE address"

    def test_never_prunes_an_address_observed_for_another_declared_mac(self, h):
        """Two uplinks; the address state attributes to A is where B actually
        is. Removing it would cut off B's claw."""
        other = "02:00:5e:00:99:99"
        h.write(allow=[UPLINK_OLD, UPLINK_NOW],
                arp_rows=[(UPLINK_NOW, "0x2", MAC), (UPLINK_OLD, "0x2", other)],
                nodes=[{"name": "A", "mac": MAC},
                       {"name": "B", "mac": other}])
        st = self._state(h, {MAC: [UPLINK_OLD]})
        r = self._run(h, "--print", st)
        assert UPLINK_OLD in r.stdout, "pruned an address another uplink occupies"

    def test_never_prunes_extra_allow(self, h):
        h.write(allow=[PEER, UPLINK_NOW], arp_rows=[(UPLINK_NOW, "0x2", MAC)],
                nodes=[{"name": "UPLINK", "mac": MAC, "extra_allow": [PEER]}])
        st = self._state(h, {MAC: [PEER]})
        r = self._run(h, "--print", st)
        assert PEER in r.stdout, "pruned an explicitly declared extra_allow"

    def test_corrupt_state_degrades_to_keep_and_report(self, h):
        """Unreadable history is not permission to delete."""
        h.write(allow=[PEER, UPLINK_OLD, UPLINK_NOW],
                arp_rows=[(UPLINK_NOW, "0x2", MAC)])
        p = h.tmp / "bad_state.json"
        p.write_text("{not json")
        r = self._run(h, "--check", str(p))
        assert UPLINK_OLD in r.stdout
        assert "unattributable" in r.stdout
