"""Drift guard for the TUI capability index (`scripts/gen_capability_index.py`).

The capability index makes the 77-handler TUI surface legible to the assistant.
It is only trustworthy if it cannot silently go stale — the SKILL.md scope note
records that a hand-maintained handler count drifted 60→64→96. This test pins
the committed `.claude/skills/meshforge/capability_index.md` to what the live
`get_all_handlers()` registry produces: add/rename/remove a handler or a menu
action without regenerating, and the suite goes red.

The generator and this test share ONE build function and ONE path constant
(honest_failure_modes #5) — the format/location live in exactly one place.
"""

import importlib.util
import re
from pathlib import Path


# Import the generator as a module — it lives in scripts/, not on the package
# path. Importing it also runs its sys.path setup for handler imports.
_SCRIPT_PATH = (
    Path(__file__).resolve().parent.parent / "scripts" / "gen_capability_index.py"
)
_spec = importlib.util.spec_from_file_location("gen_capability_index", _SCRIPT_PATH)
_gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_gen)

build_index_markdown = _gen.build_index_markdown
INDEX_PATH = _gen.INDEX_PATH


def _header_counts(markdown: str):
    """Pull (handlers, actions, sections) out of the summary line."""
    m = re.search(r"\*\*(\d+) handlers · (\d+) menu actions · (\d+) sections\*\*", markdown)
    assert m, "capability index summary line missing or reshaped"
    return int(m.group(1)), int(m.group(2)), int(m.group(3))


class TestCapabilityIndexDrift:
    def test_committed_index_matches_live_registry(self):
        """The core pin: committed file == freshly-built index. If this fails,
        the TUI command surface changed — regenerate and commit."""
        assert INDEX_PATH.exists(), (
            f"{INDEX_PATH} is missing — run "
            f"`python3 scripts/gen_capability_index.py`")
        committed = INDEX_PATH.read_text(encoding="utf-8")
        fresh = build_index_markdown()
        assert committed == fresh, (
            "capability index is STALE: it does not match the live handler "
            "registry. A handler or menu action was added/renamed/removed "
            "without regenerating. Run `python3 scripts/gen_capability_index.py` "
            "and commit the updated .claude/skills/meshforge/capability_index.md")

    def test_index_is_not_vacuous(self):
        """honest_failure_modes #1/#2 — a generator that discovered nothing
        (broken path, empty registry) must FAIL, not pass an empty file."""
        fresh = build_index_markdown()
        handlers, actions, sections = _header_counts(fresh)
        assert handlers >= 50, f"only {handlers} handlers — discovery likely broke"
        assert actions >= 50, f"only {actions} menu actions — discovery likely broke"
        assert sections >= 5, f"only {sections} sections — discovery likely broke"
        # The body must actually contain table rows, not just a header.
        assert fresh.count("|") > 200, "index has a header but almost no table rows"

    def test_index_carries_generated_warning(self):
        """The committed artifact must announce it's generated, so a hand-edit
        without regenerating is visibly wrong (and caught by the pin above)."""
        committed = INDEX_PATH.read_text(encoding="utf-8")
        assert "AUTO-GENERATED by `scripts/gen_capability_index.py`" in committed
        assert "do NOT edit by hand" in committed

    def test_red_drift_is_detected(self):
        """RED proof — the equality check is meaningful, not vacuous: a single
        mutated line must NOT equal the freshly-built index."""
        fresh = build_index_markdown()
        mutated = fresh.replace("handlers ·", "HANDLERS ·", 1)
        assert mutated != fresh
        # ...and the real committed file is the unmutated form.
        assert INDEX_PATH.read_text(encoding="utf-8") == fresh

    def test_known_capability_is_indexed(self):
        """Sanity that the generator reflects REAL registry content — a stable,
        always-visible action appears with its handler. Guards against a
        generator that emits a well-formed but empty/wrong surface."""
        fresh = build_index_markdown()
        assert "DashboardHandler" in fresh
        assert "`status`" in fresh  # Dashboard's Service Status action tag
