#!/usr/bin/env python3
"""Maintain a generated /etc/hosts block for the mf.internal fleet names.

WHY THIS EXISTS (2026-07-25)
----------------------------
m1 answers only exact (name, type) static matches locally and FORWARDS
everything else to its WAN upstream. Fleet names carry A records only, so
every AAAA query for `<name>.mf.internal` is forwarded to the internet and
comes back NODATA after ~75ms -- with no SOA, so systemd-resolved cannot
negatively cache it and pays that round trip EVERY time, forever.

Every real tool (ssh, curl, urllib, requests, getent) calls getaddrinfo with
AF_UNSPEC and therefore asks for both families. Measured on the fleet:

    12-host sweep   AF_UNSPEC 902.4 ms    AF_INET 1.7 ms
    DNS tax                   900.7 ms

So local fleet-name resolution was coupled to internet reachability. nss
`files` is consulted before `dns`, so a generated /etc/hosts block removes
both the tax and the WAN dependency -- and keeps fleet names resolving when
DNS or the uplink is down, which matters for a disaster-comms NOC.

THE HAZARD, AND HOW THIS HANDLES IT
-----------------------------------
/etc/hosts SHADOWS DNS. A stale entry is therefore worse than no entry: the
86.x segment is deliberately unreserved DHCP, and a reshuffle has already
made a healthy box look dead once (moc5, 2026-06-24). So this block is NOT
seeded from the registry's `ip_fallback` snapshot -- that would bake in a
point-in-time copy and shadow the truth with it.

It is seeded from LIVE DNS (m1's authoritative A records, ~1.2ms each), which
makes the block a maintained CACHE of the authoritative record. `--check`
re-derives from DNS and reports drift so a cron can catch a reshuffle.
`ip_fallback` is used only where DNS cannot answer, and is marked in the
output so it is visible rather than silent.

Honest-failure-mode rules enforced here:
  * DNS unreachable is UNKNOWN (exit 2), never "in sync" and never an empty
    block. Absence of evidence is not evidence of absence.
  * A run that resolves ZERO names REFUSES to write. Blindness must not be
    mistaken for an empty fleet.
  * Only the delimited managed block is ever touched; the rest of /etc/hosts
    is preserved byte-for-byte.
  * FQDNs only -- no bare short names. A bare alias would shadow the box's
    own hostname entry and the `search lan` domain.

Usage:
    python3 scripts/gen_fleet_hosts.py --print     # show the block, no root
    python3 scripts/gen_fleet_hosts.py --check     # 0 in sync, 1 drift, 2 unknown
    sudo python3 scripts/gen_fleet_hosts.py --apply
"""
from __future__ import annotations

import argparse
import os
import shutil
import socket
import struct
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Dict, List, Optional, Tuple

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from utils.fleet_naming import load_registry  # noqa: E402

HOSTS_PATH = Path("/etc/hosts")
RESOLVED_DROPIN_DIR = Path("/etc/systemd/resolved.conf.d")
RESOLV_CONF = Path("/etc/resolv.conf")
BEGIN = "# BEGIN meshforge fleet (generated by scripts/gen_fleet_hosts.py)"
END = "# END meshforge fleet"

EXIT_OK = 0
EXIT_DRIFT = 1
EXIT_UNKNOWN = 2


def _is_loopback(addr: str) -> bool:
    """127.0.0.0/8 (incl. systemd-resolved's 127.0.0.53 stub) or ::1.

    A local stub is NEVER a valid upstream here: the stub answers from
    /etc/hosts, so querying it would compare the generated block against
    ITSELF -- the self-confirming check killed on 2026-07-25. The whole
    point of this module is to reach the server that holds the zone.
    """
    return addr.startswith("127.") or addr == "::1"


def upstream_servers() -> List[str]:
    """The DNS server(s) that actually hold the fleet zone.

    Discovered, never hardcoded (MF014: no operator addresses in the repo).
    In order: the resolved drop-in that routes the fleet domain, then
    resolvectl's global server, then classic ``/etc/resolv.conf`` nameserver
    lines -- the last is what a box WITHOUT systemd-resolved uses, and
    without it this tool is undeployable there (found on kiai + moc3,
    2026-07-26: every name fell through to ip_fallback and the run correctly
    refused, but the box could never get a block at all).

    Loopback stubs are dropped at every source -- see `_is_loopback`.
    """
    servers: List[str] = []
    dropin_dir = RESOLVED_DROPIN_DIR
    if dropin_dir.is_dir():
        for conf in sorted(dropin_dir.glob("*.conf")):
            try:
                text = conf.read_text()
            except OSError:
                continue
            for line in text.splitlines():
                line = line.strip()
                if line.upper().startswith("DNS=") and "=" in line:
                    servers.extend(line.split("=", 1)[1].split())

    if not servers:
        try:
            out = subprocess.run(["resolvectl", "status"], capture_output=True,
                                 text=True, timeout=10).stdout
            for line in out.splitlines():
                if "Current DNS Server:" in line:
                    servers.append(line.split(":", 1)[1].strip())
                    break
        except (OSError, subprocess.SubprocessError):
            pass

    if not servers:
        try:
            text = RESOLV_CONF.read_text()
        except OSError:
            text = ""
        for line in text.splitlines():
            line = line.strip()
            if line.startswith("nameserver"):
                parts = line.split()
                if len(parts) >= 2:
                    servers.append(parts[1])

    seen, out_list = set(), []
    for srv in servers:
        if srv and srv not in seen and not _is_loopback(srv):
            seen.add(srv)
            out_list.append(srv)
    return out_list


def _dns_query_a(server: str, fqdn: str, timeout: float) -> Tuple[bool, Optional[str]]:
    """One UDP A query. -> (answered, ip_or_None). `answered` False means the
    server did not respond at all, which is UNKNOWN, not 'no such host'."""
    qname = b"".join(bytes([len(p)]) + p.encode() for p in fqdn.split(".")) + b"\x00"
    query = (struct.pack(">HHHHHH", 0x7A5F, 0x0100, 1, 0, 0, 0)
             + qname + struct.pack(">HH", 1, 1))
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.settimeout(timeout)
    try:
        sock.sendto(query, (server, 53))
        data, _ = sock.recvfrom(4096)
    except (socket.timeout, OSError):
        return False, None
    finally:
        sock.close()

    if len(data) < 12:
        return False, None
    _qid, _flags, qdcount, ancount, _ns, _ar = struct.unpack(">HHHHHH", data[:12])
    off = 12
    try:
        for _ in range(qdcount):
            while data[off]:
                off += data[off] + 1
            off += 5
        for _ in range(ancount):
            if data[off] & 0xC0 == 0xC0:
                off += 2
            else:
                while data[off]:
                    off += data[off] + 1
                off += 1
            rtype, _cls, _ttl, rdlen = struct.unpack(">HHIH", data[off:off + 10])
            off += 10
            if rtype == 1 and rdlen == 4:
                return True, socket.inet_ntoa(data[off:off + 4])
            off += rdlen
    except (IndexError, struct.error):
        return False, None
    return True, None          # answered, but no A record


def resolve_a(fqdn: str, timeout: float = 3.0) -> Optional[str]:
    """Authoritative IPv4 for `fqdn` from the DNS SERVER — never via NSS.

    THIS MUST NOT USE getaddrinfo(). nss `files` reads /etc/hosts before
    `dns`, and systemd-resolved also answers from /etc/hosts, so a
    getaddrinfo-based check would compare the generated block against
    ITSELF — self-confirming, and blind to exactly the DHCP reshuffle it
    exists to catch. Caught by a live drill 2026-07-25: a deliberately
    corrupted entry reported "in sync" AND survived --apply, because the
    corrupted file WAS the script's notion of truth.

    A only, on purpose: the AAAA leg is the WAN round trip this whole
    script exists to eliminate.
    """
    for server in upstream_servers():
        answered, ip = _dns_query_a(server, fqdn, timeout)
        if answered:
            return ip
    return None


def build_entries(registry) -> Tuple[List[Tuple[str, str, str]], List[str]]:
    """-> ([(ip, fqdn, source)], warnings). source is 'dns' or 'ip_fallback'."""
    domain = registry.domain or "mf.internal"
    entries: List[Tuple[str, str, str]] = []
    warnings: List[str] = []

    for alias in sorted(registry.hosts):
        host = registry.hosts[alias]
        fqdn = f"{alias}.{domain}"
        ip = resolve_a(fqdn)
        if ip:
            entries.append((ip, fqdn, "dns"))
            if host.ip_fallback and host.ip_fallback != ip:
                warnings.append(
                    f"{alias}: DNS says {ip}, registry ip_fallback says "
                    f"{host.ip_fallback} (fallback_stale)")
        elif host.ip_fallback:
            entries.append((host.ip_fallback, fqdn, "ip_fallback"))
            warnings.append(f"{alias}: DNS could not answer; used registry "
                            f"ip_fallback {host.ip_fallback}")
        else:
            warnings.append(f"{alias}: unresolvable and no ip_fallback — omitted")
    return entries, warnings


def render_block(entries: List[Tuple[str, str, str]]) -> str:
    lines = [BEGIN,
             "# DO NOT EDIT BY HAND. Regenerate with:",
             "#   sudo python3 scripts/gen_fleet_hosts.py --apply",
             "# Seeded from live DNS; 'via ip_fallback' marks a name DNS "
             "could not answer."]
    width = max((len(ip) for ip, _f, _s in entries), default=15)
    for ip, fqdn, source in entries:
        suffix = "    # via ip_fallback" if source == "ip_fallback" else ""
        lines.append(f"{ip:<{width}}  {fqdn}{suffix}")
    lines.append(END)
    return "\n".join(lines) + "\n"


def split_hosts(text: str) -> Tuple[str, Optional[str], str]:
    """-> (before, managed_block_or_None, after). Preserves everything else."""
    if BEGIN not in text:
        return text, None, ""
    before, rest = text.split(BEGIN, 1)
    if END not in rest:
        # Truncated/torn block: treat the remainder as managed so a repair
        # rewrites it rather than appending a second block.
        return before, BEGIN + rest, ""
    body, after = rest.split(END, 1)
    return before, BEGIN + body + END + "\n", after.lstrip("\n")


def current_block(path: Path) -> Optional[str]:
    if not path.exists():
        return None
    return split_hosts(path.read_text())[1]


def parse_block(block: Optional[str]) -> Dict[str, str]:
    """fqdn -> ip for the managed block (comments/markers ignored)."""
    out: Dict[str, str] = {}
    if not block:
        return out
    for line in block.splitlines():
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) >= 2:
            out[parts[1]] = parts[0]
    return out


def write_block(path: Path, block: str) -> Path:
    before, _old, after = split_hosts(path.read_text())
    if not before.endswith("\n") and before:
        before += "\n"
    new_text = before + block + (("\n" + after) if after.strip() else "")

    backup = path.with_suffix(path.suffix + ".bak-meshforge")
    shutil.copy2(path, backup)

    # Atomic replace so a crash mid-write can never leave a torn /etc/hosts.
    fd, tmp = tempfile.mkstemp(dir=str(path.parent), prefix=".hosts-mf-")
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(new_text)
        shutil.copystat(path, tmp)
        os.replace(tmp, path)
    except BaseException:
        Path(tmp).unlink(missing_ok=True)
        raise
    return backup


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--print", dest="do_print", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    ap.add_argument("--hosts-file", default=str(HOSTS_PATH))
    args = ap.parse_args()

    registry, errors = load_registry()
    if errors or registry is None:
        for err in errors:
            print(f"registry error: {err}", file=sys.stderr)
        print("UNKNOWN: registry unreadable — refusing to guess", file=sys.stderr)
        return EXIT_UNKNOWN

    entries, warnings = build_entries(registry)
    for warn in warnings:
        print(f"warn: {warn}", file=sys.stderr)

    resolved = [e for e in entries if e[2] == "dns"]
    if not resolved:
        # Every name failed DNS. That is a blind observer, not an empty
        # fleet -- never rewrite the block from this state.
        print("UNKNOWN: no name resolved via DNS — refusing to write "
              "(blindness is not an empty fleet)", file=sys.stderr)
        return EXIT_UNKNOWN

    block = render_block(entries)
    path = Path(args.hosts_file)

    if args.do_print:
        sys.stdout.write(block)
        return EXIT_OK

    have = parse_block(current_block(path))
    want = parse_block(block)

    if args.check:
        if have == want:
            print(f"in sync: {len(want)} fleet names")
            return EXIT_OK
        for fqdn in sorted(set(have) | set(want)):
            if have.get(fqdn) != want.get(fqdn):
                print(f"DRIFT {fqdn}: hosts={have.get(fqdn, '-')} "
                      f"dns={want.get(fqdn, '-')}")
        return EXIT_DRIFT

    if have == want:
        print(f"already current: {len(want)} fleet names")
        return EXIT_OK

    backup = write_block(path, block)
    verify = parse_block(current_block(path))
    if verify != want:
        print("ERROR: post-write verification failed", file=sys.stderr)
        return EXIT_UNKNOWN
    print(f"applied: {len(want)} fleet names (backup {backup})")
    return EXIT_OK


if __name__ == "__main__":
    sys.exit(main())
