#!/usr/bin/env python3
"""Generate the TUI capability index for the ``meshforge`` skill.

The 98-handler TUI surface is "dark" to the assistant unless something maps it:
the SKILL.md scope note records that the handler count alone drifted 60→64→96
because it was hand-maintained. This script derives the WHOLE command surface
(every section → handler → menu action) straight from ``get_all_handlers()`` so
it can never go stale silently — ``tests/test_capability_index.py`` fails the
build if the committed index drifts from the live registry.

Single source of truth: ``build_index_markdown()`` and ``INDEX_PATH`` are
imported by the drift test, so the format + location live in exactly one place
(honest_failure_modes #5 — two consumers of one artifact share one constant).

Usage:
    python3 scripts/gen_capability_index.py          # write the index
    python3 scripts/gen_capability_index.py --check   # exit 1 if it would change
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path
from typing import List, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
# Where the generated artifact lives — read by the skill, pinned by the test.
INDEX_PATH = REPO_ROOT / ".claude" / "skills" / "meshforge" / "capability_index.md"

# Mirror tests/conftest.py so handler imports resolve the same way the suite
# (and the real TUI) sees them: ``handlers`` + ``handler_protocol`` are top-level
# under launcher_tui, and handlers reach into ``utils`` under src.
_LAUNCHER = REPO_ROOT / "src" / "launcher_tui"
_SRC = REPO_ROOT / "src"
for _p in (str(_LAUNCHER), str(_SRC)):
    if _p not in sys.path:
        sys.path.insert(0, _p)


def _clean_desc(desc: str) -> str:
    """Make a whiptail-column-aligned label legible + table-safe.

    Menu descriptions are space-padded for the TUI's two-column layout
    ("Label      Detail"); collapse the gap to an em-dash separator and escape
    pipes so they cannot break the markdown table.
    """
    desc = desc.replace("|", r"\|")
    desc = re.sub(r"\s{2,}", " — ", desc.strip())
    return desc


def collect_handlers() -> List[dict]:
    """Introspect every registered handler into a plain, sortable structure.

    Returns one dict per handler with: handler_id, class name, menu_section, and
    its menu items (tag, cleaned description, feature flag). A handler that
    cannot be constructed, or whose ``menu_items()`` raises, is recorded with an
    ``error`` field rather than dropped — a silently-omitted handler would read
    as "this part of the UI does nothing" (honest_failure_modes #1/#9).
    """
    from handlers import get_all_handlers
    from handler_protocol import TUIContext

    # A neutral context: no dialog, no feature flags. ``feature_enabled()``
    # returns True for everything, so the index shows the FULL surface
    # independent of any deployment profile (keeps the artifact deterministic).
    neutral_ctx = TUIContext(dialog=None)

    rows: List[dict] = []
    for cls in get_all_handlers():
        entry = {
            "class": cls.__name__,
            "handler_id": getattr(cls, "handler_id", "") or "",
            "section": getattr(cls, "menu_section", "") or "",
            "items": [],
            "error": None,
        }
        try:
            inst = cls()
            if hasattr(inst, "set_context"):
                inst.set_context(neutral_ctx)
            # Instance attrs win over class attrs if the handler sets them.
            entry["handler_id"] = getattr(inst, "handler_id", entry["handler_id"]) or entry["handler_id"]
            entry["section"] = getattr(inst, "menu_section", entry["section"]) or entry["section"]
            items = inst.menu_items()
            for tag, desc, flag in items:
                entry["items"].append((str(tag), _clean_desc(str(desc)), flag or ""))
        except Exception as exc:  # noqa: BLE001 — surfaced, not swallowed
            entry["error"] = f"{type(exc).__name__}: {exc}"
        rows.append(entry)
    return rows


def build_index_markdown() -> str:
    """Render the capability index markdown. Pure function of the code/registry.

    Deterministic: sections sorted, handlers sorted by id, items sorted by tag.
    No environment, clock, or live-service state enters the output, so the
    committed file is a stable golden the drift test can pin exactly.
    """
    rows = collect_handlers()

    sections: dict = {}
    for r in rows:
        sections.setdefault(r["section"], []).append(r)

    total_handlers = len(rows)
    total_items = sum(len(r["items"]) for r in rows)
    total_sections = len(sections)
    errored = [r["class"] for r in rows if r["error"]]

    out: List[str] = []
    out.append("# MeshForge TUI Capability Index")
    out.append("")
    out.append("> AUTO-GENERATED by `scripts/gen_capability_index.py` — do NOT edit by hand.")
    out.append("> Pinned to the live handler registry by `tests/test_capability_index.py`;")
    out.append("> if that test fails, the TUI surface changed — regenerate with")
    out.append("> `python3 scripts/gen_capability_index.py` and commit the result.")
    out.append(">")
    out.append("> Purpose: make the TUI's command surface legible so it isn't \"dark\" to")
    out.append("> the assistant (the handler-count-drift problem). Asked \"can the TUI do")
    out.append("> X?\", grep this file for the capability, then open the handler under")
    out.append("> `src/launcher_tui/handlers/`.")
    out.append("")
    out.append(
        f"**{total_handlers} handlers · {total_items} menu actions · "
        f"{total_sections} sections** (all derived from `get_all_handlers()`, never hardcoded)."
    )
    out.append("")
    out.append(
        "A non-empty **Flag** means the action only appears when that "
        "deployment-profile feature is enabled (blank = always visible)."
    )
    out.append("")

    if errored:
        # Honest surface: a handler whose menu_items could not be read is a
        # real gap, shown loudly — never folded into a healthy-looking summary.
        out.append("> ⚠️ **Handlers whose menu items could not be read this build:** "
                   + ", ".join(sorted(errored)) + ". See the per-section error rows below.")
        out.append("")

    for section in sorted(sections):
        handlers = sorted(sections[section], key=lambda r: (r["handler_id"], r["class"]))
        title = section if section else "(no section)"
        out.append(f"## `{title}`")
        out.append("")
        out.append("| Action tag | Description | Flag | Handler |")
        out.append("|---|---|---|---|")
        any_row = False
        for r in handlers:
            if r["error"]:
                out.append(f"| _(error)_ | ⚠️ {r['error']} |  | {r['class']} |")
                any_row = True
                continue
            if not r["items"]:
                # Lifecycle/dispatch-only handler: listed so the surface is
                # complete, not silently absent.
                out.append(f"| _(no menu items)_ | lifecycle / dispatch only |  | {r['class']} |")
                any_row = True
                continue
            for tag, desc, flag in sorted(r["items"], key=lambda t: t[0]):
                flag_cell = f"`{flag}`" if flag else ""
                out.append(f"| `{tag}` | {desc} | {flag_cell} | {r['class']} |")
                any_row = True
        if not any_row:
            out.append("| _(none)_ |  |  |  |")
        out.append("")

    return "\n".join(out).rstrip("\n") + "\n"


def main(argv: List[str]) -> int:
    check_only = "--check" in argv[1:]
    content = build_index_markdown()
    if check_only:
        existing = INDEX_PATH.read_text(encoding="utf-8") if INDEX_PATH.exists() else ""
        if existing != content:
            print(f"DRIFT: {INDEX_PATH} is out of date — run "
                  f"`python3 scripts/gen_capability_index.py`", file=sys.stderr)
            return 1
        print(f"OK: {INDEX_PATH} matches the live registry.")
        return 0
    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(content, encoding="utf-8")
    rel = os.path.relpath(INDEX_PATH, REPO_ROOT)
    print(f"Wrote {rel} ({len(content)} bytes).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
