import sys
sys.path.insert(0, "/opt/meshforge/src")
from utils.deployment_profiles import list_profiles

ps = list_profiles()
flags = sorted({f for p in ps for f in p.feature_flags})

out = []
w = out.append
w("# Deployment Profiles\n")
w("> **GENERATED from the SSOT** — `src/utils/deployment_profiles.py`.")
w("> Regenerate with `python3 scripts/gen_profiles_doc.py` after changing a")
w("> profile. This file was MISSING for months while `CLAUDE.md` linked to it")
w("> (found 2026-09-15); a doc that does not exist is worse than none, because")
w("> the link implies it was checked.\n")
w("A profile declares **what this box runs**. It is stored in")
w("`~/.config/meshforge/deployment.json` under the `profile` key.")
w("(resolved via `utils.paths.get_real_user_home()` — MF001: the raw stdlib "
  "home lookup returns /root under sudo and breaks config persistence.)\n")
w("⚠️ **`deployment.json` is SHARED with the fleet-role system.**")
w("`scripts/provision_role.py` owns the `role`, `service_overrides` and")
w("`organ_expectations` keys in the same file. Every writer must")
w("read-merge-write; `save_profile()` does, and REFUSES (returns `False`)")
w("rather than overwrite a file it cannot parse.\n")
w("## The profiles\n")
w("| Profile | Display name | Required services | Required packages |")
w("|---|---|---|---|")
for p in ps:
    rs = ", ".join(f"`{s}`" for s in p.required_services) or "—"
    rp = ", ".join(f"`{s}`" for s in p.required_packages) or "—"
    w(f"| `{p.name.value}` | {p.display_name} | {rs} | {rp} |")
w("")
w("## Feature flags\n")
w("A flag gates a TUI menu action via `TUIContext.feature_enabled()`.")
w("Wired 2026-09-16 (plan Phase 3). Three rules govern it:\n")
w("1. **Only a SAVED profile gates.** The launcher calls `load_profile()`,")
w("   never `load_or_detect_profile()` — detection reads which services are")
w("   RUNNING, so gating on it would hide the RNS menu on a box whose rnsd")
w("   is down, removing the tool at the moment it is needed. A box with no")
w("   `profile` key in `deployment.json` shows all 115 actions, unchanged.")
w("2. **A profile MARKS a row, it never removes one.** A row outside the")
w("   profile renders with an `[off]` prefix, keeps its own label, and")
w("   explains itself when selected — naming the profile, the flag, and")
w("   the in-app way to change it. Menus are the same length with or")
w("   without a profile. Hiding was tried first and reversed the same day")
w("   (2026-09-16): someone new to the domain cannot go looking for a")
w("   capability they have never been shown, and un-hiding needed a")
w("   session override, a reserved tag through eleven menu loops, and a")
w("   fix for the escape hatch scrolling off a 24x80 terminal.")
w("3. **One vocabulary, both sides.** `FEATURE_FLAGS` in")
w("   `utils/deployment_profiles.py` is the SSOT. The guards in")
w("   `tests/test_profile_gating.py` fail if a profile declares a flag no")
w("   handler consumes, or a handler gates on a word no profile declares.")
w("   Both had happened: `maps` gated nothing, `fleet_management` could")
w("   never close.\n")
w("| Profile | " + " | ".join(f"`{f}`" for f in flags) + " |")
w("|---|" + "---|" * len(flags))
for p in ps:
    cells = " | ".join("yes" if p.feature_flags.get(f) else "—" for f in flags)
    w(f"| `{p.name.value}` | {cells} |")
w("")
w("## Descriptions\n")
for p in ps:
    w(f"- **`{p.name.value}`** — {p.description}")
    if p.optional_services:
        w(f"  - optional services: " + ", ".join(f"`{s}`" for s in p.optional_services))
    if p.optional_packages:
        w(f"  - optional packages: " + ", ".join(f"`{s}`" for s in p.optional_packages))
w("")
w("## Selecting a profile\n")
w("```bash")
w("python3 src/launcher.py --profile gateway   # explicit")
w("python3 src/launcher.py                     # auto-detect")
w("```")
w("")
w("In the TUI: **Configuration > MeshForge Settings > Deployment Profile**.")
w("(That action was broken from its introduction until 2026-09-15 — it")
w("imported a `get_profile` symbol that does not exist and passed a string to")
w("`save_profile()`, so every selection reported `Failed to set profile`.)\n")
w("## Consumers\n")
w("`src/launcher.py`, `src/daemon.py`, `src/daemon_config.py`,")
w("`src/setup_wizard.py`, `src/utils/startup_health.py`, and")
w("`src/launcher_tui/handlers/settings.py`.\n")
w("## Not a fleet role\n")
w("A **profile** says what software features this box offers. A **role**")
w("(`docs/fleet_roles.yaml`, `scripts/provision_role.py`) says what the fleet")
w("expects this box to run. They are different vocabularies that happen to")
w("share one file. When they disagree, the role is what the fleet's organs")
w("check against.\n")

open("/opt/meshforge/.claude/foundations/deployment_profiles.md", "w").write("\n".join(out))
print("wrote", len("\n".join(out)), "chars")
