#!/usr/bin/env python3
"""gen_claw_pinhole.py — keep the NATS pinhole pointed at the claw's ACTUAL uplink.

WHY THIS EXISTS (2026-07-29, live 6.5 h outage)
-----------------------------------------------
WireClaw firmware cannot send NATS credentials, so the brain box default-denies
TCP 4222 and admits a small hardcoded source allowlist. One of those entries is
the WAN address of the AREDN node that fronts the claw's own /28.

That address is assigned by a router this fleet does NOT administer. When the
node rebooted, its lease moved; the pinhole kept the old address; every SYN from
a perfectly healthy claw hit `tcp dport 4222 drop` for 6.5 hours. The claw was
associated the whole time, held its lease, and retried the correct broker.
/proc/net/nf_conntrack showed SYN_SENT [UNREPLIED] with reply packets=0.

The class is honest_failure_modes #5: ONE constant (the uplink's address) held
in TWO independent places — someone else's DHCP and our firewall — which drift.

WHY NOT A DHCP RESERVATION
--------------------------
Because fleet reachability must not be contingent on config in a router we do
not own. This fleet already made that call once, for names: the /etc/hosts
fleet block exists so names resolve "with DNS or the uplink down", and the
router-side fix was explicitly rejected for coupling the fleet to a box outside
our domain. A reservation is the same coupling one layer lower. The fleet owns
its own reachability, so the fleet re-derives the address it needs.

IDENTITY ANCHOR
---------------
The uplink is identified by MAC, not by address — the MAC is the thing that does
not change when a lease moves. Its current address comes from /proc/net/arp,
ATF_COM (0x2) entries only: an INCOMPLETE (0x0) row is a resolution that FAILED,
and probing a stale address manufactures exactly such a row carrying the target
MAC. A flags-blind reader invents drift out of its own footprints.

SAFETY INVARIANTS (this script rewrites a FIREWALL)
--------------------------------------------------
1. It only ever owns the delimited region below. Never another chain, table, or
   rule. Everything outside the markers is passed through byte-for-byte.
2. It NEVER renders an empty allowlist. An empty render would cut off every
   claw — the exact outage this exists to prevent — so it refuses and reports
   unobservable instead.
3. An unobserved declared node HOLDS its previous entry rather than being
   dropped. Absence of evidence is not evidence the node is gone
   (honest_failure_modes #2); dropping on blindness would sever a working claw.
4. It ADDS the observed address and REPORTS entries it cannot attribute, rather
   than deleting them. Silently removing firewall rules it cannot account for
   is not a repair.
5. Every write is syntax-validated with `nft -c -f` BEFORE install, and verified
   by RE-READING afterwards — never by trusting the writer's exit code
   (calibrated_claims #7).

EXIT CODES (same contract as gen_fleet_hosts.py)
    0 = in sync / applied and verified
    1 = drift (with --check) or apply failed
    2 = UNOBSERVABLE — could not determine the truth. Never triggers a write.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile

BEGIN = "# BEGIN meshforge claw pinhole (generated by scripts/gen_claw_pinhole.py)"
END = "# END meshforge claw pinhole"

DEFAULT_NFT_PATH = "/etc/nftables.conf"
DEFAULT_ARP_PATH = "/proc/net/arp"
DEFAULT_PORT = 4222
_ATF_COM = 0x2

_SADDR_RE = re.compile(r"ip\s+saddr\s*\{([^}]*)\}\s*tcp\s+dport\s+(\d+)\s+accept")


def _config_path() -> str:
    try:
        sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
        from utils.paths import get_real_user_home
        home = str(get_real_user_home())
    except Exception:
        home = os.path.expanduser("~")
    return os.path.join(home, ".config", "meshforge", "claw_uplink_nodes.json")


def read_declared(path: str):
    """(nodes, error). nodes = [{name, mac, extra_allow?}]. error != None -> unobservable."""
    if not os.path.exists(path):
        return [], "no declaration at %s" % path
    try:
        with open(path) as f:
            doc = json.load(f)
    except (OSError, ValueError) as e:
        return [], "declaration unreadable (%s)" % e.__class__.__name__
    if not isinstance(doc, list):
        return [], "declaration is not a list"
    out = []
    for n in doc:
        if isinstance(n, dict) and str(n.get("mac") or "").strip():
            out.append(n)
    if not out:
        return [], "declaration has no entries carrying a mac"
    return out, None


def arp_locations(arp_path: str):
    """({mac_lower: [ip]}, error). COMPLETE entries only — see IDENTITY ANCHOR."""
    try:
        with open(arp_path) as f:
            lines = f.read().splitlines()
    except OSError as e:
        return {}, "%s unreadable (%s)" % (arp_path, e.__class__.__name__)
    out: dict = {}
    for line in lines[1:]:
        parts = line.split()
        if len(parts) < 4:
            continue
        ip, flags_s, mac = parts[0], parts[2], parts[3]
        try:
            flags = int(flags_s, 16)
        except ValueError:
            continue
        if not (flags & _ATF_COM):
            continue
        out.setdefault(mac.lower(), []).append(ip)
    return out, None


def split_region(text: str):
    """(before, region_or_None, after)."""
    if BEGIN not in text:
        return text, None, ""
    before, rest = text.split(BEGIN, 1)
    if END not in rest:
        return before, "", ""          # torn block: region is discarded, rebuilt
    body, after = rest.split(END, 1)
    return before, body, after.lstrip("\n")


def current_allow(text: str, port: int):
    """Allowlist currently in effect anywhere in the file (region or hand-written)."""
    found: list = []
    for m in _SADDR_RE.finditer(text):
        if int(m.group(2)) != port:
            continue
        found += [p.strip() for p in m.group(1).split(",") if p.strip()]
    return sorted(set(found))


def render(allow, port: int) -> str:
    return "\n".join([
        BEGIN,
        "\t\t# Source allowlist for the claw NATS bus. Rendered from the uplink",
        "\t\t# MAC in claw_uplink_nodes.json resolved through the neighbour table,",
        "\t\t# because the address is assigned by a router outside this domain.",
        "\t\t# Do not hand-edit: scripts/gen_claw_pinhole.py --apply owns this block.",
        "\t\tip saddr { %s } tcp dport %d accept" % (", ".join(allow), port),
        END,
    ]) + "\n"


def plan(nft_path: str, arp_path: str, port: int, config_path: str):
    """(allow, notes, error). error != None => UNOBSERVABLE, never write."""
    notes = []
    nodes, err = read_declared(config_path)
    if err:
        return None, notes, err
    locs, err = arp_locations(arp_path)
    if err:
        return None, notes, err
    try:
        with open(nft_path) as f:
            text = f.read()
    except OSError as e:
        return None, notes, "%s unreadable (%s)" % (nft_path, e.__class__.__name__)

    existing = current_allow(text, port)
    allow = set()
    attributed = set()

    for n in nodes:
        mac = str(n["mac"]).lower().strip()
        name = str(n.get("name") or mac)
        seen = [ip for ip in (locs.get(mac) or [])]
        if seen:
            allow.update(seen)
            attributed.update(seen)
            for ip in seen:
                if ip not in existing:
                    notes.append("uplink %s now at %s (was not admitted)" % (name, ip))
        else:
            # INVARIANT 3: hold, never drop on blindness.
            held = [ip for ip in existing]
            allow.update(held)
            notes.append("uplink %s not in neighbour table — HOLDING existing "
                         "allowlist (blindness is not departure)" % name)
        for ip in (n.get("extra_allow") or []):
            allow.add(str(ip)); attributed.add(str(ip))

    # INVARIANT 4: keep what we cannot attribute, and say so.
    unattributed = [ip for ip in existing if ip not in attributed]
    if unattributed:
        allow.update(unattributed)
        notes.append("keeping %d unattributable entry(ies) %s — prune by hand if "
                     "stale (a repair must not silently delete firewall rules)"
                     % (len(unattributed), ",".join(sorted(unattributed))))

    # INVARIANT 2: never render nobody.
    if not allow:
        return None, notes, ("render would admit NOBODY — refusing (that is the "
                             "outage this prevents)")
    return sorted(allow), notes, None


def apply_region(nft_path: str, allow, port: int, dry: bool = False):
    """(ok, message). Validates then verifies by re-reading."""
    with open(nft_path) as f:
        text = f.read()
    before, region, after = split_region(text)
    new_region = render(allow, port)
    if region is None:
        return False, ("no managed region in %s — add the markers around the "
                       "pinhole line first (deliberate: this script will not "
                       "guess where in a firewall to insert itself)" % nft_path)
    new_text = before + new_region + (after if after else "")
    if new_text == text:
        return True, "already current"
    if dry:
        return True, "would rewrite managed region"

    d = os.path.dirname(nft_path) or "."
    fd, tmp = tempfile.mkstemp(dir=d, prefix=".claw_pinhole.")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(new_text)
        # INVARIANT 5: validate BEFORE install.
        chk = subprocess.run(["nft", "-c", "-f", tmp],
                             capture_output=True, text=True, timeout=20)
        if chk.returncode != 0:
            return False, "nft -c rejected the render: %s" % (chk.stderr or "").strip()
        shutil.copy2(nft_path, nft_path + ".bak-claw-pinhole")
        shutil.copystat(nft_path, tmp)
        os.replace(tmp, nft_path)
        tmp = None
    finally:
        if tmp and os.path.exists(tmp):
            os.unlink(tmp)

    rc = subprocess.run(["systemctl", "reload", "nftables"],
                        capture_output=True, text=True, timeout=30)
    if rc.returncode != 0:
        rc = subprocess.run(["systemctl", "restart", "nftables"],
                            capture_output=True, text=True, timeout=30)
        if rc.returncode != 0:
            return False, "wrote config but nftables reload FAILED: %s" % (
                rc.stderr or "").strip()
    # INVARIANT 5: verify by observing the artifact.
    live = subprocess.run(["nft", "list", "ruleset"],
                          capture_output=True, text=True, timeout=20)
    if live.returncode == 0:
        got = current_allow(live.stdout, port)
        missing = [ip for ip in allow if ip not in got]
        if missing:
            return False, ("reload reported success but the LIVE ruleset does not "
                           "admit %s" % ",".join(missing))
    return True, "applied and verified in the live ruleset"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--print", dest="do_print", action="store_true")
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--apply", action="store_true")
    ap.add_argument("--nft-file", default=DEFAULT_NFT_PATH)
    ap.add_argument("--arp-file", default=DEFAULT_ARP_PATH)
    ap.add_argument("--config", default=None)
    ap.add_argument("--port", type=int, default=DEFAULT_PORT)
    a = ap.parse_args()
    cfg = a.config or _config_path()

    allow, notes, err = plan(a.nft_file, a.arp_file, a.port, cfg)
    for n in notes:
        print("note: %s" % n)
    if err:
        print("UNOBSERVABLE: %s" % err)
        return 2

    if a.do_print:
        sys.stdout.write(render(allow, a.port))
        return 0

    try:
        with open(a.nft_file) as f:
            live_allow = current_allow(f.read(), a.port)
    except OSError as e:
        print("UNOBSERVABLE: cannot re-read %s (%s)" % (a.nft_file, e.__class__.__name__))
        return 2

    if a.check:
        if live_allow == allow:
            print("in sync: pinhole admits %s" % ", ".join(allow))
            return 0
        print("DRIFT: pinhole admits %s; should admit %s"
              % (", ".join(live_allow) or "nobody", ", ".join(allow)))
        return 1

    ok, msg = apply_region(a.nft_file, allow, a.port)
    print(("applied: " if ok else "FAILED: ") + msg)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
