#!/bin/bash
#
# Upgrade USB-direct mode to native meshtasticd
#
# This enables the web UI on port 9443 for USB radios by installing
# the native meshtasticd daemon instead of using CLI-only mode.
#
# Usage:
#   sudo bash scripts/upgrade_to_native.sh
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# OpenSUSE Build Service repo for native meshtasticd
OBS_BASE_URL="https://download.opensuse.org/repositories/network:/Meshtastic:/beta"

echo -e "${CYAN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║     Upgrade to Native meshtasticd (Web UI enabled)        ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root${NC}"
   echo "Please run: sudo bash $0"
   exit 1
fi

# ─────────────────────────────────────────────────────────────────
# Detect OS for repo
# ─────────────────────────────────────────────────────────────────
detect_os_repo() {
    if [[ ! -f /etc/os-release ]]; then
        echo "Debian_12"
        return
    fi

    source /etc/os-release

    case "$ID" in
        debian)
            case "$VERSION_ID" in
                12) echo "Debian_12" ;;
                13) echo "Debian_13" ;;
                *)  echo "Debian_12" ;;
            esac
            ;;
        raspbian)
            echo "Raspbian_${VERSION_ID:-12}"
            ;;
        ubuntu)
            case "$VERSION_ID" in
                24.04|24.10) echo "xUbuntu_24.04" ;;
                22.04)       echo "xUbuntu_22.04" ;;
                *)           echo "xUbuntu_24.04" ;;
            esac
            ;;
        *)
            echo "Debian_12"
            ;;
    esac
}

# ─────────────────────────────────────────────────────────────────
# Check current state
# ─────────────────────────────────────────────────────────────────
echo -e "${CYAN}[1/5] Checking current installation...${NC}"

if command -v meshtasticd &>/dev/null; then
    VERSION=$(meshtasticd --version 2>/dev/null || echo "unknown")
    echo -e "  ${GREEN}✓ Native meshtasticd already installed (${VERSION})${NC}"
    echo -e "  ${YELLOW}Skipping installation, will update config only${NC}"
    ALREADY_INSTALLED=true
else
    echo -e "  ${CYAN}Native meshtasticd not installed${NC}"
    ALREADY_INSTALLED=false
fi

# Check for USB device
USB_DEV=""
for dev in /dev/ttyUSB* /dev/ttyACM*; do
    if [[ -e "$dev" ]]; then
        USB_DEV="$dev"
        break
    fi
done

if [[ -n "$USB_DEV" ]]; then
    echo -e "  ${GREEN}✓ USB device found: ${USB_DEV}${NC}"
else
    echo -e "  ${YELLOW}⚠ No USB device found (will configure anyway)${NC}"
fi

# ─────────────────────────────────────────────────────────────────
# Install native meshtasticd
# ─────────────────────────────────────────────────────────────────
if ! $ALREADY_INSTALLED; then
    echo -e "${CYAN}[2/5] Installing native meshtasticd...${NC}"

    OS_REPO=$(detect_os_repo)
    echo -e "  ${CYAN}Detected OS: ${BOLD}${OS_REPO}${NC}"

    REPO_URL="${OBS_BASE_URL}/${OS_REPO}/"
    KEY_URL="${OBS_BASE_URL}/${OS_REPO}/Release.key"

    echo -e "  ${CYAN}Adding Meshtastic repository...${NC}"
    echo "deb ${REPO_URL} /" > /etc/apt/sources.list.d/meshtastic.list
    curl -fsSL "$KEY_URL" | gpg --dearmor > /etc/apt/trusted.gpg.d/meshtastic.gpg 2>/dev/null

    echo -e "  ${CYAN}Updating package lists...${NC}"
    apt-get update -qq

    echo -e "  ${CYAN}Installing meshtasticd...${NC}"
    if apt-get install -y meshtasticd; then
        VERSION=$(meshtasticd --version 2>/dev/null || echo "installed")
        echo -e "  ${GREEN}✓ Native meshtasticd installed (${VERSION})${NC}"
    else
        echo -e "${RED}Failed to install meshtasticd${NC}"
        echo -e "${YELLOW}Check: https://meshtastic.org/docs/software/linux-native/${NC}"
        exit 1
    fi
else
    echo -e "${CYAN}[2/5] Skipping install (already present)${NC}"
fi

# ─────────────────────────────────────────────────────────────────
# Configure meshtasticd for USB
# ─────────────────────────────────────────────────────────────────
echo -e "${CYAN}[3/5] Configuring meshtasticd for USB...${NC}"

MESHTASTICD_CONFIG_DIR="/etc/meshtasticd"
mkdir -p "$MESHTASTICD_CONFIG_DIR"/{available.d,config.d,ssl}
chmod 700 "$MESHTASTICD_CONFIG_DIR/ssl"

# Create USB device config in config.d/
if [[ -n "$USB_DEV" ]]; then
    cat > "$MESHTASTICD_CONFIG_DIR/config.d/usb-device.yaml" << USB_CONFIG
# USB Serial Radio Configuration
# Generated by upgrade_to_native.sh
Lora:
  SerialPath: ${USB_DEV}
USB_CONFIG
    echo -e "  ${GREEN}✓ Created USB device config for ${USB_DEV}${NC}"
fi

# Ensure main config.yaml has Webserver section
if [[ -f "$MESHTASTICD_CONFIG_DIR/config.yaml" ]]; then
    if ! grep -q "Webserver:" "$MESHTASTICD_CONFIG_DIR/config.yaml"; then
        cat >> "$MESHTASTICD_CONFIG_DIR/config.yaml" << 'ADD_WEB'

Webserver:
  Port: 9443
  RootPath: /usr/share/meshtasticd/web
ADD_WEB
        echo -e "  ${GREEN}✓ Added Webserver section to config.yaml${NC}"
    fi
else
    cat > "$MESHTASTICD_CONFIG_DIR/config.yaml" << 'MAIN_CONFIG'
---
Lora:
  # Module: auto  # Disabled — select hardware via TUI or copy template to config.d/

Logging:
  LogLevel: info

Webserver:
  Port: 9443
  RootPath: /usr/share/meshtasticd/web

General:
  MaxNodes: 200
  MaxMessageQueue: 100
  ConfigDirectory: /etc/meshtasticd/config.d/
  AvailableDirectory: /etc/meshtasticd/available.d/
MAIN_CONFIG
    echo -e "  ${GREEN}✓ Created config.yaml with Webserver enabled${NC}"
fi

# ─────────────────────────────────────────────────────────────────
# Update NOC config
# ─────────────────────────────────────────────────────────────────
echo -e "${CYAN}[4/5] Updating MeshForge NOC config...${NC}"

NOC_CONFIG="/etc/meshforge/noc.yaml"
if [[ -f "$NOC_CONFIG" ]]; then
    # Update daemon type from usb-direct to native-usb
    if grep -q 'daemon: "usb-direct"' "$NOC_CONFIG" 2>/dev/null || \
       grep -q "daemon: usb-direct" "$NOC_CONFIG" 2>/dev/null; then
        sed -i 's/daemon: "usb-direct"/daemon: "native-usb"/' "$NOC_CONFIG"
        sed -i 's/daemon: usb-direct/daemon: "native-usb"/' "$NOC_CONFIG"
        echo -e "  ${GREEN}✓ Updated daemon type to native-usb${NC}"
    elif grep -q 'daemon: "native-usb"' "$NOC_CONFIG" 2>/dev/null; then
        echo -e "  ${GREEN}✓ Already configured for native-usb${NC}"
    else
        echo -e "  ${YELLOW}⚠ Could not find daemon setting to update${NC}"
    fi

    # Update daemon_type in services section too
    sed -i 's/daemon_type: "usb-direct"/daemon_type: "native-usb"/' "$NOC_CONFIG"
else
    echo -e "  ${YELLOW}⚠ NOC config not found at ${NOC_CONFIG}${NC}"
fi

# ─────────────────────────────────────────────────────────────────
# Create/update systemd service
# ─────────────────────────────────────────────────────────────────
MESHTASTICD_BIN=$(command -v meshtasticd)
if [[ -n "$MESHTASTICD_BIN" ]]; then
    cat > /etc/systemd/system/meshtasticd.service << SERVICE
[Unit]
Description=Meshtastic Daemon (Native USB)
Documentation=https://meshtastic.org
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/etc/meshtasticd
ExecStart=${MESHTASTICD_BIN} -c /etc/meshtasticd/config.yaml
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
SERVICE

    systemctl daemon-reload
    echo -e "  ${GREEN}✓ Updated systemd service${NC}"
fi

# ─────────────────────────────────────────────────────────────────
# Start services
# ─────────────────────────────────────────────────────────────────
echo -e "${CYAN}[5/5] Starting services...${NC}"

systemctl enable meshtasticd 2>/dev/null
systemctl restart meshtasticd

sleep 3

if systemctl is-active --quiet meshtasticd; then
    echo -e "  ${GREEN}✓ meshtasticd is running${NC}"

    # Check web port
    LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")
    sleep 2
    if timeout 2 bash -c "echo >/dev/tcp/${LOCAL_IP}/9443" 2>/dev/null; then
        echo -e "  ${GREEN}✓ Web client responding on port 9443${NC}"
    else
        echo -e "  ${YELLOW}⚠ Web client not responding yet (may need more time)${NC}"
    fi
else
    echo -e "  ${RED}✗ meshtasticd failed to start${NC}"
    echo -e "  ${YELLOW}Check: sudo journalctl -u meshtasticd -n 20${NC}"
fi

# ─────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Upgrade Complete!                            ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${CYAN}Web Client:${NC}"
LOCAL_IP=$(hostname -I 2>/dev/null | awk '{print $1}' || echo "localhost")
echo -e "  ${BOLD}https://${LOCAL_IP}:9443${NC}"
echo ""
echo -e "${CYAN}Commands:${NC}"
echo -e "  ${GREEN}meshforge-web${NC}         - Open web client"
echo -e "  ${GREEN}meshforge-noc --status${NC} - Check service status"
echo ""
